# Generated by Django 5.2.6 on 2025-09-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='items',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='sweet',
            name='user',
        ),
    ]
