# Generated by Django 5.2.6 on 2025-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_remove_sweet_address_remove_sweet_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='icon',
            field=models.CharField(default='🍬', help_text='Emoji icon for the sweet', max_length=10),
        ),
    ]
