# Generated by Django 5.2.6 on 2025-09-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_sweet_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sweets.order')),
                ('sweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweets.sweet')),
            ],
        ),
    ]
