# Generated by Django 5.2.6 on 2025-09-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sweets',
        ),
    ]
